clusterName: production-lab
region: ap-south-1
serviceAccount:
  create: false
  name: aws-load-balancer-controller
replicaCount: 2
resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 200m
    memory: 500Mi
nodeSelector:
  workload: application

